version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: MyProject.API/Dockerfile
    container_name: myproject-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Kết nối Redis bằng tên service trong network
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
    networks:
      - myproject-network

  redis:
    image: redis:7.4
    container_name: myproject-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - myproject-network

volumes:
  redis_data:

networks:
  myproject-network:
    driver: bridge
